import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, ExternalLink, FolderGit2 } from "lucide-react";
import { Reveal } from "@/components/animations/reveal";
import { SectionHeading } from "@/components/section-heading";
import { projects } from "@/data/projects";

function ProjectVisual({name,image}:{name:string;image?:string}){
  if(image)return <div className="relative aspect-[16/10] min-h-72 overflow-hidden bg-elevated"><Image src={image} alt={`${name} live website homepage`} fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover object-top transition duration-500 group-hover:scale-[1.025]"/></div>;
  return <div className="relative min-h-72 overflow-hidden bg-elevated p-6"><div className="absolute inset-0 bg-[linear-gradient(to_right,var(--line)_1px,transparent_1px),linear-gradient(to_bottom,var(--line)_1px,transparent_1px)] bg-[size:32px_32px] opacity-50"/><div className="relative mx-auto mt-4 max-w-md rounded-xl border border-line bg-bg p-3 shadow-2xl"><div className="flex h-7 items-center gap-1.5 border-b border-line px-1"><i className="size-1.5 rounded-full bg-muted/30"/><i className="size-1.5 rounded-full bg-muted/30"/><i className="size-1.5 rounded-full bg-muted/30"/></div><div className="grid grid-cols-[70px_1fr] gap-3 pt-3"><div className="space-y-2 border-r border-line pr-2">{[60,42,50,35].map((w,k)=><i key={k} className="block h-1.5 rounded bg-line" style={{width:`${w}%`}}/>)}</div><div><div className="mb-3 h-16 rounded-lg bg-accent/10"/><div className="grid grid-cols-3 gap-2">{[1,2,3].map(x=><div key={x} className="h-20 rounded-lg border border-line bg-surface"/>)}</div></div></div></div></div>;
}

export function Projects(){return <section id="projects" className="section shell scroll-mt-20"><SectionHeading eyebrow="03 / Selected work" title="Products built for real operations." description="A selection of platforms where product engineering meets dependable backend systems and production delivery."/><div className="space-y-8">{projects.map((p,i)=><Reveal key={p.slug}><article className="project-card group grid overflow-hidden rounded-2xl border border-line bg-surface lg:grid-cols-2"><div className={`${i%2?"lg:order-2 lg:border-l":"lg:border-r"} border-line`}><ProjectVisual name={p.name} image={p.image}/></div><div className={`p-7 sm:p-10 ${i%2?"lg:order-1":""}`}><div className="flex items-center justify-between"><span className="font-mono text-xs text-accent">0{i+1}</span><FolderGit2 size={18} className="text-muted"/></div><h3 className="mt-7 text-3xl font-semibold tracking-tight">{p.name}</h3><p className="mt-4 max-w-xl leading-7 text-muted">{p.description}</p><div className="mt-6 flex flex-wrap gap-2">{p.technologies.map(x=><span key={x} className="rounded-lg border border-line px-2.5 py-1 text-xs text-muted">{x}</span>)}</div><div className="mt-7 border-t border-line pt-6"><p className="text-xs uppercase tracking-wider text-muted">Engineering focus</p><p className="mt-2 text-sm leading-6">{p.focus.join(" · ")}</p></div><div className="mt-7 flex flex-wrap gap-5 text-sm"><Link href={`/projects/${p.slug}`} className="group/link inline-flex items-center gap-2 font-medium">View case study <ArrowUpRight size={15} className="transition group-hover/link:translate-x-0.5 group-hover/link:-translate-y-0.5"/></Link>{p.repository&&<a href={p.repository} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-muted hover:text-fg">GitHub <ExternalLink size={14}/></a>}{p.liveUrl&&<a href={p.liveUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-muted hover:text-fg">Live site <ExternalLink size={14}/></a>}</div></div></article></Reveal>)}</div></section>}
